Homeworks: ActiveDocument Struct Reference
ActiveDocument Struct Reference
#include <ActiveDocument.h>
Public Member Functions
ActiveDocument (const int Index)
void CreatePrimitive (const Color color, const Form form) override
void RemovePrimitive (const int Index) override
void PrintPrimitiveProperty (const int Index) const override
void PrintAllPrimitives () const override
int GetPrimitivesCount () const override
int GetIndex () const override
void SetAsVisible () override
void SetAsInvisible () override
~ActiveDocument ()=default
Public Member Functions inherited from IDocument
virtual void CreatePrimitive (const Color color, const Form form)=0
virtual void RemovePrimitive (const int Index)=0
virtual void PrintPrimitiveProperty (const int Index) const =0
virtual void PrintAllPrimitives () const =0
virtual int GetPrimitivesCount () const =0
virtual int GetIndex () const =0
virtual void SetAsVisible ()=0
virtual void SetAsInvisible ()=0
virtual ~IDocument ()=default
Static Public Member Functions
static std::unique_ptr< IDocument > CreateDocument (const int Index)
Private Attributes
std::map< int, std::unique_ptr< IPrimitive > > m_primitives
int m_count {0}
int m_index {-1}
bool m_isActive {false}
Detailed Description
Definition at line 10 of file ActiveDocument.h.
Constructor & Destructor Documentation
ActiveDocument()
ActiveDocument::ActiveDocument (const int Index)
Definition at line 5 of file ActiveDocument.cpp.
                                              : m_index(Index)
{
    std::cout << "Create new ActiveDocument " << m_index << "\n";
};
~ActiveDocument()
ActiveDocument::~ActiveDocument () default
Member Function Documentation
CreateDocument()
std::unique_ptr< IDocument > ActiveDocument::CreateDocument (const int Index) static
Definition at line 10 of file ActiveDocument.cpp.
{
    return std::make_unique<ActiveDocument>(Index);
}
Referenced by EditorModel::AddActiveDocument(), and user::ClickImportDocumentFromFileButton().
CreatePrimitive()
void ActiveDocument::CreatePrimitive (const Color color, const Form form) override virtual
Implements IDocument.
Definition at line 15 of file ActiveDocument.cpp.
{
    const auto Index{m_count++};
    std::cout << "Add new Primitive " << Index << " to m_primitives map\n";
    m_primitives[Index] = std::make_unique<Primitive>(Index, color, form);
}
GetIndex()
int ActiveDocument::GetIndex () const override virtual
Implements IDocument.
Definition at line 50 of file ActiveDocument.cpp.
{
    return m_index;
}
Referenced by PrintAllPrimitives(), SetAsInvisible(), and SetAsVisible().
GetPrimitivesCount()
int ActiveDocument::GetPrimitivesCount () const override virtual
Implements IDocument.
Definition at line 45 of file ActiveDocument.cpp.
{
    return m_primitives.size();
}
PrintAllPrimitives()
void ActiveDocument::PrintAllPrimitives () const override virtual
Implements IDocument.
Definition at line 35 of file ActiveDocument.cpp.
{
    std::cout << "\n******** Document " << GetIndex() << " ********\n";
    for (const auto& primitive : m_primitives)
    {
        primitive.second->PrintProperties();
    }
    std::cout << "****** end Document " << GetIndex() << " ******\n\n";
}
PrintPrimitiveProperty()
void ActiveDocument::PrintPrimitiveProperty (const int Index) const override virtual
Implements IDocument.
Definition at line 29 of file ActiveDocument.cpp.
{
    // TODO: error handling access to a non-existent index
    m_primitives.at(Index)->PrintProperties();
}
RemovePrimitive()
void ActiveDocument::RemovePrimitive (const int Index) override virtual
Implements IDocument.
Definition at line 22 of file ActiveDocument.cpp.
{
    // TODO: error handling access to a non-existent index
    std::cout << "Remove primitive " << Index << "\n";
    m_primitives.erase(Index);
}
SetAsInvisible()
void ActiveDocument::SetAsInvisible () override virtual
Implements IDocument.
Definition at line 61 of file ActiveDocument.cpp.
{
    std::cout << "Set document " << GetIndex() << " as invisible\n";
    m_isActive = false;
}
SetAsVisible()
void ActiveDocument::SetAsVisible () override virtual
Implements IDocument.
Definition at line 55 of file ActiveDocument.cpp.
{
    std::cout << "Set document " << GetIndex() << " as visible\n";
    m_isActive = true;
}
Member Data Documentation
m_count
int ActiveDocument::m_count {0} private
Definition at line 29 of file ActiveDocument.h.
Referenced by CreatePrimitive().
m_index
int ActiveDocument::m_index {-1} private
Definition at line 30 of file ActiveDocument.h.
Referenced by ActiveDocument(), and GetIndex().
m_isActive
bool ActiveDocument::m_isActive {false} private
Definition at line 31 of file ActiveDocument.h.
Referenced by SetAsInvisible(), and SetAsVisible().
m_primitives
std::map<int, std::unique_ptr<IPrimitive> > ActiveDocument::m_primitives private
Definition at line 28 of file ActiveDocument.h.
Referenced by CreatePrimitive(), GetPrimitivesCount(), PrintAllPrimitives(), PrintPrimitiveProperty(), and RemovePrimitive().
The documentation for this struct was generated from the following files:
homework_05/graphics_editor/model/data/document/ActiveDocument.h
homework_05/graphics_editor/model/data/document/ActiveDocument.cpp