Homeworks: IDocument Struct Reference
IDocument Struct Reference abstract
#include <IDocument.h>
Public Member Functions
virtual void CreatePrimitive (const Color color, const Form form)=0
virtual void RemovePrimitive (const int Index)=0
virtual void PrintPrimitiveProperty (const int Index) const =0
virtual void PrintAllPrimitives () const =0
virtual int GetPrimitivesCount () const =0
virtual int GetIndex () const =0
virtual void SetAsVisible ()=0
virtual void SetAsInvisible ()=0
virtual ~IDocument ()=default
Detailed Description
Definition at line 6 of file IDocument.h.
Constructor & Destructor Documentation
~IDocument()
virtual IDocument::~IDocument () virtual default
Member Function Documentation
CreatePrimitive()
virtual void IDocument::CreatePrimitive (const Color color, const Form form) pure virtual
Implemented in ActiveDocument.
Referenced by EditorController::CreateGraphicsPrimitive().
GetIndex()
virtual int IDocument::GetIndex () const pure virtual
Implemented in ActiveDocument.
Referenced by EditorModel::AddActiveDocument(), EditorView::CloseDocument(), EditorController::ExportDocument(), EditorView::OpenDocument(), and EditorView::UpdateDocument().
GetPrimitivesCount()
virtual int IDocument::GetPrimitivesCount () const pure virtual
Implemented in ActiveDocument.
PrintAllPrimitives()
virtual void IDocument::PrintAllPrimitives () const pure virtual
Implemented in ActiveDocument.
Referenced by EditorView::OpenDocument(), and EditorView::UpdateDocument().
PrintPrimitiveProperty()
virtual void IDocument::PrintPrimitiveProperty (const int Index) const pure virtual
Implemented in ActiveDocument.
RemovePrimitive()
virtual void IDocument::RemovePrimitive (const int Index) pure virtual
Implemented in ActiveDocument.
Referenced by EditorController::RemoveGraphicsPrimitive().
SetAsInvisible()
virtual void IDocument::SetAsInvisible () pure virtual
Implemented in ActiveDocument.
Referenced by EditorController::CreateNewDocument(), EditorController::ExportDocument(), and EditorController::ImportDocument().
SetAsVisible()
virtual void IDocument::SetAsVisible () pure virtual
Implemented in ActiveDocument.
Referenced by EditorController::CreateNewDocument(), EditorController::ExportDocument(), and EditorController::ImportDocument().
The documentation for this struct was generated from the following file:
homework_05/graphics_editor/model/data/document/IDocument.h