Homeworks: user Namespace Reference
user Namespace Reference
Functions
void ClickCreateNewDocumentButton ()
void ClickImportDocumentFromFileButton ()
void ClickExportDocumentToFileButton ()
void ClickCreateGraphicsPrimitive (const Color color, const Form form)
void ClickRemoveGraphicsPrimitive ()
Variables
auto editorController = EditorController::CreateController()
Function Documentation
ClickCreateGraphicsPrimitive()
void user::ClickCreateGraphicsPrimitive (const Color color, const Form form) inline
Definition at line 32 of file main.cpp.
{
    std::cout << "\n[user] ClickCreateGraphicsPrimitive\n";
    editorController->CreateGraphicsPrimitive(color, form);
    std::cout << "---------------------\n";
}
Referenced by main().
ClickCreateNewDocumentButton()
void user::ClickCreateNewDocumentButton () inline
Definition at line 8 of file main.cpp.
{
    std::cout << "\n[user] ClickCreateNewDocumentButton\n";
    editorController->CreateNewDocument();
    std::cout << "---------------------\n";
}
Referenced by main().
ClickExportDocumentToFileButton()
void user::ClickExportDocumentToFileButton () inline
Definition at line 24 of file main.cpp.
{
    // TODO: only currently visible document are exported
    std::cout << "\n[user] ClickExportDocumentToFileButton\n";
    editorController->ExportDocument();
    std::cout << "---------------------\n";
}
Referenced by main().
ClickImportDocumentFromFileButton()
void user::ClickImportDocumentFromFileButton () inline
Definition at line 15 of file main.cpp.
{
    std::cout << "\n[user] ClickImportDocumentFromFileButton\n";
    constexpr auto ExtermalIndex{100};
    auto externalDocument = ActiveDocument::CreateDocument(ExtermalIndex);
    editorController->ImportDocument(std::move(externalDocument));
    std::cout << "---------------------\n";
}
Referenced by main().
ClickRemoveGraphicsPrimitive()
void user::ClickRemoveGraphicsPrimitive () inline
Definition at line 39 of file main.cpp.
{
    std::cout << "\n[user] ClickRemoveGraphicsPrimitive\n";
    // TODO: no primitives indexes getting method yet
    editorController->RemoveGraphicsPrimitive(0);
    std::cout << "---------------------\n";
}
Referenced by main().
Variable Documentation
editorController
auto user::editorController = EditorController::CreateController()
Definition at line 6 of file main.cpp.
Referenced by ClickCreateGraphicsPrimitive(), ClickCreateNewDocumentButton(), ClickExportDocumentToFileButton(), ClickImportDocumentFromFileButton(), and ClickRemoveGraphicsPrimitive().