Homeworks: homework_02/helpers/filters.h File Reference
filters.h File Reference
#include "helpers.h"
Functions
void ReverseLexicographicallySort (ip_pool &ipTuples)
ip_pool FilterIpPool (const ip_pool &IpPool, const ip_array &Filter)
ip_pool FilterIpPoolByAny (const ip_pool &IpPool, const int Value)
Function Documentation
FilterIpPool()
ip_pool FilterIpPool (const ip_pool & IpPool, const ip_array & Filter) inline
Definition at line 10 of file filters.h.
{
    ip_pool filteredIpPool;
    for (const auto& Ip : IpPool)
    {
        if ((Filter.at(0) == AnyByte ||
                Ip.at(0) == Filter.at(0)) &&
            (Filter.at(1) == AnyByte ||
                Ip.at(1) == Filter.at(1)) &&
            (Filter.at(2) == AnyByte ||
                Ip.at(2) == Filter.at(2)) &&
            (Filter.at(3) == AnyByte ||
                Ip.at(3) == Filter.at(3)))
        {
            filteredIpPool.push_back(Ip);
        }
    }
    return filteredIpPool;
}
Referenced by main(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
FilterIpPoolByAny()
ip_pool FilterIpPoolByAny (const ip_pool & IpPool, const int Value) inline
Definition at line 32 of file filters.h.
{
    ip_pool filteredIpPool;
    for (const auto& Ip : IpPool)
    {
        if (Ip.at(0) == Value ||
            Ip.at(1) == Value ||
            Ip.at(2) == Value ||
            Ip.at(3) == Value)
        {
            filteredIpPool.push_back(Ip);
        }
    }
    return filteredIpPool;
}
Referenced by main(), and TEST_F().
ReverseLexicographicallySort()
void ReverseLexicographicallySort (ip_pool & ipTuples) inline
Definition at line 5 of file filters.h.
{
    std::sort(ipTuples.begin(), ipTuples.end(), std::greater<ip_array>());
}
Referenced by main(), and TEST_F().